require 'git'

 = <<-IMG.split("\n").map {|row| row.split('')}
XXABXXXXXBXABXXXXABXXXXABXXABXXXXXXXXXXXXXXXXXXXXXXX
XXABXXXXABXABXXXXABXXXXABXXABXXXXXXXXXXXXXXXXXXXXXXX
XXABXXXXABXABXXXXABXXXXXABBBXXXXXXXXXXXXXXXXXXXXXXXX
XXABXXXXABXABXXXXABXXXXXXABXXXXXXXXXXXXXXXXXXXXXXXXX
XXABXXXXABXABXXXXABXXXXXXABXXXXXXXXXXXXXXXXXXXXXXXXX
XXABBBBXABXABBBBXABBBBXXXABXXXXXXXXXXXXXXXXXXXXXXXXX
XXXAAAXXXBXXAAAXXXAAAXXXXABXXXXXXXXXXXXXXXXXXXXXXXXX
IMG

days = 24*60*60
monday = Time.now - 52*7*days
monday += monday.monday? ? 0 : (7 - monday.wday) * days

A = []
B = []
.each_with_index do |row, wday|
  row.each_with_index do |char, weeks|
    if char == 'A'
      A << monday + (wday + weeks*7) * days
    elsif char == 'B'
      B << monday + (wday + weeks*7) * days
    end
  end
end
